name: symfony

services:
  php:
    container_name: app
    build: docker/php
    volumes:
      - .:/app
    environment:
      APP_ENV: dev

  caddy:
    container_name: caddy
    image: caddy:2-alpine
    depends_on:
      - php
    ports:
      - "80:80"
    volumes:
      - ./docker/caddy/Caddyfile:/etc/caddy/Caddyfile:ro
      - .:/app

  database:
    container_name: db
    image: mysql:8.4
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: app
      MYSQL_USER: app
      MYSQL_PASSWORD: password
    volumes:
      - db_data:/var/lib/mysql
    ports:
      - "3306:3306"

  redis:
    container_name: redis
    image: redis:7-alpine
    ports:
      - "6379:6379"

  mailer:
    container_name: mailhog
    image: mailhog/mailhog
    ports:
      - "1025:1025"
      - "8025:8025"

  encore:
    container_name: encore
    image: node:20
    platform: linux/amd64
    working_dir: /php
    command: sh -c "npm install --force && npm run dev-server"
    volumes:
      - .:/php
    ports:
      - "8080:8080"


volumes:
  db_data:
